.catalog:
  name: Gitlab Runner
  version: alpine-v1.2.0
  description: |
    Gitlab Runner
  minimum_rancher_version: v0.56.0
  maintainer: "Javy Liu <liuzhenyuan@meituan.com>"
  uuid: gitlab-runner-0
  questions:
    - variable: "gitlab_ci_url"
      description: "Gitlab CI URL"
      label: "url:"
      required: true
      default: "http://git.example.com/ci"
      type: "string"
    - variable: "gitlab_ci_token"
      description: "Gitlab CI token"
      label: "token:"
      required: true
      type: "password"
    - variable: "gitlab_ci_description"
      description: "Gitlab CI description"
      label: "description:"
      required: true
      type: "string"
      default: "My Docker Runner"
    - variable: "gitlab_ci_image"
      description: "Gitlab CI image"
      label: "image:"
      required: true
      type: "string"
      default: "docker:latest"

