.catalog:
  name: Gitlab Runner
  version: alpine-v1.2.0
  description: |
    Gitlab Runner
  minimum_rancher_version: v0.56.0
  maintainer: "Javy Liu <liuzhenyuan@meituan.com>"
  uuid: gitlab-runner-0
  questions:
    - variable: "gitlab_hostname"
      description: "Gitlab hostname"
      label: "Hostname:"
      required: true
      default: "git.example.com"
      type: "string"

