.catalog:
  name: Gitlab Community
  version: 8.8.2-0
  description: |
    Gitlab CE is a free GitHub alternative
  minimum_rancher_version: v0.56.0
  maintainer: "Alexis Ducastel <alexis@ducastel.net>"
  uuid: gitlab-0
  questions:
    - variable: "gitlab_hostname"
      description: "Gitlab hostname"
      label: "Hostname:"
      required: true
      default: "git.example.com"
      type: "string"
    - variable: ssh_port
      description: "ssh port to access gitlab cli"
      label: "SSH Port"
      required: true
      default: "10022" 
      type: "int"
    - variable: http_port
      description: "http port to access gitlab webui"
      label: "Http Port"
      required: true
      default: "10080" 
      type: "int"
    - variable: https_port
      description: "https port to access gitlab webui"
      label: "Https Port"
      required: true
      default: "10443" 
      type: "int"
gitlab-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

gitlab-data:
  scale: 1
  retain_ip: true

