drone-server:
  image: docker.repo.waimai.sankuai.info/drone/drone:0.5.0
  ports:
    - ${public_port}:8000/tcp
  environment:
    REMOTE_DRIVER: ${remote_driver}
    REMOTE_CONFIG: ${remote_config}
    DATABASE_DRIVER: ${database_driver}
    DATABASE_CONFIG: ${database_config}
    PLUGIN_PARAMS: ${plugin_params}
  volumes_from:
    - drone-data-volume
  volume:
    - /var/run/docker.sock:/var/run/docker.sock
  labels: 
    io.rancher.sidekicks: drone-data-volume
  external_links:
    - ${database_service}:database

## Do not change below. Could cause data loss in upgrade.
drone-data-volume:
  image: docker.repo.waimai.sankuai.info/busybox
  net: none
  command: /bin/true
  labels:
    io.rancher.container.start_once: 'true'
  volumes:
    - /var/lib/drone
    - /etc/drone
    - /opt/rancher
