.catalog:
  name: Demo
  version: v0.0.1
  description: |
    Demo Project
  uuid: demo-0
  questions:
    - variable: "scale"
      description: "Number of Etcd nodes"
      label: "Number of Nodes:"
      required: true
      default: 1
      type: "int"
demo:
  scale: "${scale}"
